---
title: "Exporatory Analysis"
output: html_document
---

## The Dog Name Trends of New York

### Authors

Annie Yuan, Yimin Tang, Denny Wu, Joanne Lu

### Date

Winter 2022

### Abstract

Our main goal in this research is to find any possible relationships between the cost and type of housing available, and the type/breed of dog that an owner chooses to get. From this data set, we hope to answer questions that will be beneficial to future dog owners as this will provide insight about dogs living in a densely populated area that some may find helpful. This is important because there have been many situations where dogs are abandoned or given to a shelter because their former owner realized it did not have the time or resources to care for them.

### Keywords

Dogs, Name Trends, Dog Names, New York

### Introduction  

With a population of over 8.4 million in 2015, New York is an extremely large and diverse city, and houses dogs of many ages and breeds in all five of its boroughs. The city is extremely dense population-wise, and this has resulted in a high cost of living. Yet despite this, New Yorkers are still able to accommodate their pets into their living situation. By analyzing a data set about dogs located in New York, we will be able to find valuable insights about the most common dog breeds living there, and think critically about why that is the case.

The research questions we are aiming to answer using our data set are:  
- How does the cost of housing and type of housing available (house, apartment, etc.) in each borough affect the size of dogs that owners choose to get?  
- Just how popular are the most popular dog names?  
- Was there a trend in any of the years where many people gave their dogs unconventional/unpopular names?

The answers to these questions may be valuable for future dog owners (especially in dense cities like New York), as they may be interested in what type of dogs are best suited for their housing situation. This is important because there are various factors that go into caring for a dog, and choosing a dog that doesn’t fit your lifestyle or housing situation may result in neglect of the dog. And on a more lighthearted note, the data would give these same people inspiration for potential dog names, and they are also able to look at the name trends that have taken place throughout the years.

### Related Work  

In a city where the population is so dense, finding affordable housing is difficult, especially for dog owners. In [this article](https://www.nytimes.com/2013/03/31/realestate/what-pet-owners-must-do-to-get-new-york-apartments.html) by *The New York Times*, stories were obtained from dog owners that went through the struggle of finding a home for themselves and their dog (Rosenblum). They asked about the types of dogs they had, the pricing of their apartment, and the process of finding the right home for their dog. The owners often had to settle for rentals that were further away, smaller, and more expensive in order to accommodate their pet. One person mentions how the age of her dog also prevented her from buying many apartments due to the amount of stairs.  

In [this article](https://www.nytimes.com/2013/04/04/garden/the-art-of-naming-a-dog.html), *The New York Times* discusses what goes on in naming a dog (Hoffman). There are general rules that most experts recommend. For example, they recommend avoiding names that could sound like a command, as this could confuse the dog.  

[This paper](https://www.mdpi.com/2076-2615/4/3/409/htm) by Emily Weiss and others talks about how bigger dogs in New York and Washington D.C. are surrendered more often than smaller dogs (Weiss, et al.). They surveyed owners at animal shelters that were giving up dogs and asked them twenty-six questions in an attempt to find a common reason behind why people gave them up. They found that the majority of New York respondents were living in apartments while most respondents in D.C. were living in single family homes. However, when they were asked for additional reasons for giving up the dog, only 14% of New York respondents listed housing issues.

#### References  
Hoffman, Jan. “You Named Me Brutus? Really?” *The New York Times*, 3 Apr. 2013, https://www.nytimes.com/2013/04/04/garden/the-art-of-naming-a-dog.html.

Rosenblum, Constance. “What Pet Owners Must Do to Get New York Apartments.” *The New York Times*, 29 Mar. 2013, https://www.nytimes.com/2013/03/31/realestate/what-pet-owners-must-do-to-get-new-york-apartments.html.  

Weiss, Emily, et al. “Large Dog Relinquishment to Two Municipal Facilities in New York City and Washington, D.C.: Identifying Targets for Intervention.” *MDPI*, Multidisciplinary Digital Publishing Institute, 8 July 2014, https://www.mdpi.com/2076-2615/4/3/409/htm.

### The Dataset

The data set was originally discovered through the visualization “Dog Names in New York City”, and was found on the NYC government website. The csv file for the data set that corresponds to this visualization was found in [this GitHub repository](https://github.com/Kaz-A/dog_names/).

The data were collected by the NYC Department of Health, and it was based on results from 2015.

It is not clear what methods were used to collect the data, but we can infer that the data were collected through questionnaires.

With the increased number of pet dogs, people are interested in potential names for them. It is possible that the names may indicate naming trends that reflect cultural or background changes. To illustrate, in some areas, there may be more dogs with one particular name than in other areas. To answer this question, we want to analyze the data of dogs’ names and what information these data could give. The purpose of collecting these data is to analyze the change and popularity in dog names.

There are 111,650 observations in total.

There are 5 features in the data, which are AnimalName, AnimalGender, AgeAsOf2015, BreedName, and Borough.

There are possible limitations within our data. The data were collected in 2015, which was roughly 7 years ago as of the time of this writing. Trends change over time, so the popular names that owners want to give to their dogs may change as well. Because of this, this data set may not be representative of the dog name trends today. Additionally, it is possible that not every dog owner in New York was counted in the data, and therefore it may not be entirely accurate.

### Implications

Assuming that we answer our research questions, our findings may be able to help designers and policymakers create further changes that would benefit dog owners, specifically owners of large dogs. In densely populated areas like most of New York, many apartments don’t allow their tenants to own large dogs, and there could be many reasons for this. But as a result, a lot of new and inexperienced dog owners may adopt a large dog (or one that will grow up to be large in the future), only to realize that they won’t be allowed to keep it. The dog may end up in a shelter hoping to finding a new home, but there’s no guarantee, especially since many homes in the New York area don’t allow large dogs in the first place. Future designers may want to keep this in mind by designing housing that’s more friendly towards large dogs, which will certainly keep dogs out of the overpopulated shelters.

Another reason why large dogs aren’t allowed in most apartments is because they’re seen as highly disruptive, yet a well-trained large dog can be less disruptive than a small dog or even a human toddler, for example. So policymakers can view this data and possibly set new rules and regulations to allow more owners of large dogs to live in apartments with their pets if the owner can prove that their dog is well-behaved enough to be there.

### Limitations & Challenges
The features of the data set only include the animal name, gender, and age in 2015. Since we only know their age and not when the name was given to them, it will be difficult to predict the trend of dog names over the years. To combat this, we will choose to assume that most of the dogs were named the same year they were born in order to stay consistent within our data. And using this assumption, we will be able to analyze name trends over time. Also, due to the limited features in the data set, our topic we are able to analyze are also limited. For example, our data do not explain the reasoning behind why the owner chose that particular name for their dog, which means that we are unable to analyze the reason why certain names are more popular than others. Additionally, the data were collected only for dog names in New York, which may not be representative or applicable to other locations in the U.S., or in other parts of the world.

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
dog_data <- dog_data %>% 
  filter(BreedName != "Unknown")

breed_n <- dog_data %>%
  group_by(BreedName) %>%
  summarize(n = n()) %>% 
  filter(BreedName != "Unknown") %>% 
  top_n(20)

top_5 <- 3853 + 4200 + 5528 + 6659 + 6978
top_5to10 <- 3195 + 2763 + 2525 + 2093 + 1970
top_10to15 <- 1897 + 1774 + 1759 + 1751 + 1718
top_15to20 <- 1480 + 1315 + 1289 + 1267 + 1242
other <- nrow(dog_data) - sum(breed_n$n)

Name <- c("top_5", "top_5to10", "top_10to15", "top_15to20", "other")
n <- c(top_5, top_5to10, top_10to15, top_15to20, other)

data <- data.frame(Name, n)

ggplot(data, aes(x = "", y = n, fill = Name)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() +
  labs(title = "Comparing the percentage of the number of top 20 name")
```
We try to find the top 20 popular dog name in NYC. By comparing the number of the top 20 names in the whole population, we can find how the top 20 names have a big weight in all names. With the effective information in the data, there are 14323 different names in total. We named the other 14303 names as "other" for more convenient comparing. From our bar chart, we can see that the number of the top 20 names are even greater than the number of other names. The number of top 5 names even take up more than 25%. Hope this will be helpful for the owner who wanted to give their dog an unique name.

### Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
